export const UPDATE_LOADING = 'UPDATE_LOADING'

export const UPDATE_UPLOADING = 'UPDATE_UPLOADING'

export const UPDATE_SUB_LOADING="UPDATE_SUB_LOADING"

export const UPDATE_ALERT_CONFIG="UPDATE_ALERT_CONFIG"

export const UPDATE_CONFIRM_CONFIG="UPDATE_CONFIRM_CONFIG"

export const UPDATE_PROMPT_CONFIG="UPDATE_PROMPT_CONFIG"

export const UPDATE_SYNC_MSG_LIST="UPDATE_SYNC_MSG_LIST"

export const UPDATE_CART_INFO="UPDATE_CART_INFO"

export const UPDATE_USER_INFO="UPDATE_USER_INFO"

export const UPDATE_SYNC_NUMS="UPDATE_SYNC_NUMS"

export const UPDATE_GLOBAL_JOB = 'UPDATE_GLOBAL_JOB'